# Netlify "kitchen sink" example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml

localhost_development:
  backend:
    name: file-system
    api_root: /api
  display_url: http://localhost:8000
  publish_mode: simple

backend:
  name: github
  repo: erikdstock/gatsby-starter-sidebar-docs # change
  branch: master

media_folder: static/assets
public_folder: assets
site_url: https://quizzical-babbage-45160a.netlify.com
publish_mode: editorial_workflow

collections:
  # A Collection with a fixed group of pages (files)
  - name: pages
    label: Pages
    format: frontmatter
    files:
      - file: "content/pages/about.mdx"
        label: "About"
        name: "about"
        # All fields except `body` will be rendered as frontmatter for markdown posts
        fields:
          - {
              label: "Collection Name",
              name: "collectionName",
              default: "pages",
              widget: "hidden", # Just stick this value^ on the frontmatter
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Ordering",
              name: "ordering",
              widget: "number",
              valueType: "float",
            }
          - { label: "Body", name: "body", widget: "mdx" }

  # A not-fixed collection uses the `folder` path relative to root
  - name: sectionOne
    label: Section One
    format: frontmatter # Files get a yaml frontmatter section (everything but body field)
    create: true # Allowed to create new files; used with `folder|extension|format|slug` below (rather than `files` array)
    folder: content/pages/section-one # Where to look and save
    extension: "mdx" # Format to find and save
    slug: "{{slug}}"
    fields:
      - {
          label: "Collection Name",
          name: "collectionName",
          widget: "hidden",
          default: "pages",
        }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - {
          label: Ordering,
          name: "ordering",
          widget: "number",
          valueType: "float",
        }
      - { label: Description, name: description, widget: text }
      - { label: Tags, name: tags, widget: list }
      - { label: Body, name: body, widget: mdx }

  - name: blog
    label: Blog
    format: frontmatter
    create: true
    folder: content/blog
    extension: "mdx"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Collection Name",
          name: "collectionName",
          widget: "hidden",
          default: "blog",
        }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Tags, name: tags, widget: list }
      - { label: Body, name: body, widget: mdx }
